#현재 사용 피시에 깔려있는 dockr engin 버전에 따라 사용하는 compose file format version이 다르다. - 현재 도커 엔진 버전 : 20.10.8
# https://docs.docker.com/compose/compose-file/compose-file-v3/ 참조 
version: '3'

services:
  xmd-auth-svc-back1:
    container_name: xmd-auth-svc-back1
    build:
      context: . 
      dockerfile: ./Dockerfile
    ports:
      - '3401:3401'
    entrypoint: ["npm", "run"]
    command: jwtstart1       
    restart: 'on-failure'

  xmd-auth-svc-back2:
    container_name: xmd-auth-svc-back2
    build:
      context: . 
      dockerfile: ./Dockerfile
    ports:
      - '3402:3402'
    entrypoint: ["npm", "run"]
    command: jwtstart2 
    restart: 'on-failure'    

  xmd-auth-svc-back3:
    container_name: xmd-auth-svc-back3
    build:
      context: . 
      dockerfile: ./Dockerfile
    ports:
      - '3403:3403'
    entrypoint: ["npm", "run"]
    command: jwtstart3 
    restart: 'on-failure'    
